spring.application.name=HSF-Group-Project

# kết nối sql server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=hsf_group_project;encrypt=true;trustServerCertificate=true;

# driver
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# tài khoản mật khẩu
spring.datasource.username=sa
spring.datasource.password=123

#
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# đặt cổng tomcat
server.port=9999

# đặt UTF-8
spring.thymeleaf.encoding=UTF-8

# F5 tự load trình duyệt
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html








